### ISSUE TITLE
Modify SONAR-netCDF4 convention file

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopype#596]
This issue is related to #570 and #519, which deal with a restructuring of the `EchoData` object. 

In order to account for this restructuring, we need to allow for the conversion of past `EchoData` objects into this new form. This is particularly necessary in `open_converted`. 

To make this conversion easier, it is necessary to add some slight modifications to [1.0.yml](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/echodata/convention/1.0.yml). We need to either add `coords` for each group e.g. 

```
groups:
  environment:
    name: Environment
    description: contains information relevant to acoustic propagation through water.
    coords: ['frequency' , 'ping_time']
    ep_group: Environment
```

or add the coordinates into `variable_and_varattributes` for each group in `1.0.yml`. 

If anyone has a different suggestion, please let me know!

@leewujung @emiliom @lsetiawan

**Comment by leewujung** [comment]
The coordinates currently specified in this yml file is **not** exhaustive, but for v0.6.0 I suggest that we take a minimalist approach to only take care of breaking changes that users will see or use immediately, such as via `open_converted`.

Anything that is missing but non-breaking, we can take care of in the following v0.6.X.

**Comment by b-reyes** [comment]
If we want to take the minimalist approach, then I suggest we just add `coords` to each group (the first suggestion above). This will allow us to address the change from `range_bin` --> `range_sample` and the reorganization of the Beam groups.

**Comment by leewujung** [comment]
> add coords to each group

This would work. 

From what I can remember atm, here are what we will need to change/add into the yml:
1. `Beam`: `Beam_group1`
2. `Beam_power` when exists : `Beam_group2`
3. `range_bin`: `range_sample`
4. `frequency`: `channel_id`
5. Along with the `channel_id` change, we add a new data variable `frequency_nominal` to retain the frequency information
6. `range`: `echo_range`  (this shouldn't be needed, since this is only after calibration)

@b-reyes : How about if you do the first 3, and @emiliom and I take care of the rest once your first batch of changes are in? since we still need to take care of #566.

**Comment by b-reyes** [comment]
@leewujung I believe the first two items are already done in `1.0.yml`. See the `name` portion below

https://github.com/OSOceanAcoustics/echopype/blob/1afc16aeb9b7ed67d39006ac9192f13b9d76e4b6/echopype/echodata/convention/1.0.yml#L35-L47

Now that you mentioned items 4, 5, and 6, do you think we should just go with a full blown description of the groups and associated data variables? That way we are not modifying `1.0.yml` in a significant way in the future? I know this may overlap with pydantic, but it seems like we could just replace `1.0.yml` with pydantic or have it be part of pydantic.  For example, we could do the following:

```
groups:
  environment:
    name: Environment
    description: contains information relevant to acoustic propagation through water.
    ep_group: Environment
    variables:
      absorption_indicative:
        coords: ['frequency', 'ping_time']
      sound_speed_indicative:
        coords: ['frequency', 'ping_time']
```

Then when we are checking the file we know exactly what to change when doing the conversions.

**Comment by leewujung** [comment]
> I believe the first two items are already done in 1.0.yml.

Oh great! I hadn't looked into the file so that's great!

> Now that you mentioned items 4, 5, and 6, do you think we should just go with a full blown description of the groups and associated data variables

I think for v0.6.0 we can aim for having just the coordinate part of every group, to minimize delay to roll out the release, and add description for all data variables in later v0.6.X -- on this second part, @emiliom should definitely chime in here because I think he has something that captures the v.1 convention entirely that could be used/useful in including _everything_ into this yml.

**Comment by b-reyes** [comment]
Just to clarify @leewujung is your vote for the addition of `coords` to each group too or do you think this should be done differently?

**Comment by b-reyes** [comment]
I just realized that the coordinates of a particular group can change depending on the echosounder that you are using. Is this correct? If so, I think we need to be a little more specific when putting the coordinates. For example, we can do the following:

```
groups:
  environment:
    name: Environment
    description: contains information relevant to acoustic propagation through water.
    ep_group: Environment
    coords_ek60: ['frequency' , 'ping_time']
    coords_ek80: ['ping_time']
    coords_azfp: ['ping_time']
    coords_ad2cp: ['ping_time', 'ping_time_burst', 'ping_time_average', 'ping_time_echosounder']
```

**Comment by leewujung** [comment]
I think this would be fine since for only the coordinates this should be manageable. 

Coordinates really should not be something we change very often. I think once we are in compliance with v1 the transition to v2 would be smoother. The proposed changes in v2 I know of are more in the addition type, aiming to accommodate new data types (such as ADCP) or clarification/specification (such as transducer orientation).

Note the AD2CP format has **not** been reviewed carefully (and that is low on the priority list, we should build up the processing capability first for the other echosounders), so as long as thing "work" for that format, we can save the elaboration to later.

**Comment by emiliom** [comment]
I've gone over #598. I see the convenience of leveraging `1.0.yml` to also support the backwards compatibility and mapping need. But, `1.0.yml` was intended to be the source of SONAR-netCDF4 v1 truth defined in a single place, regardless. Adding the sensor-specific coords would change this. Plus, for clarity we'd want to specify what those coords refer to: the echopype 0.5.x coords, the 0.6.x coords, or both (ie, the mapping)? The mapping would be needed if the intent is to enable reading of 0.5.x files and conversion to 0.6.x, which will involve renaming the coords, among other things.

Note also that the beam group mappings from 0.5.x to 0.6.x is also iffy. Here's what the current version (in `dev`) of `1.0.yml` has for the 2 beam groups included (I've removed the `description` attribute):
```yml
  beam:
    name: Sonar/Beam_group1
    ep_group: Sonar/Beam_group1
  beam_power:
    name: Sonar/Beam_group2
    ep_group: Sonar/Beam_group2
```

It sounds like the intent is to use `beam` and `beam_power` as the 0.5.x group names that get mapped to the corresponding entry in `ep_group` (`Sonar/Beam_group1` and `Sonar/Beam_group2`). But that would fail as is because the names of the 0.5.x  groups in the nc/zarr files actually start with an uppercase letter: `Beam` and `Beam_power`. That could easily be accommodated in code by capitalizing the first letter, but that's layering one thing on top of another. Also, I think our retention of `beam` and `beam_power` in 1.0.yml was intended as transitional.

**Ultimately**, 1.0.yml should have only one Beam group, b/c that's how the convention is defined: the template for all beam groups is defined once, and it should be reused in as many beam groups as needed. But since we've had a hard-wired reliance on those two possible groups (`beam` and `beam_power`), the current arrangement helps ease the transition.

Finally, in #574 I started a shift to define sensor-specific information in the `set_group_SENSOR.py` modules. Currently it's just the beam group name(s) and descriptions. eg, see [set_groups_ek80.py#L17](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/convert/set_groups_ek80.py#L17).

I'll end this long comment here and start a new one with suggestions.
